###############################################################################
#Ansible Role for KPMG Challenge                                              #
#File Name: main.yml                                                          #
###############################################################################
#Developer - Arun Kumar Lakshmi Narayanan                                     #
###############################################################################
#Purpose Of The Script : To install PostgreSQL on RHEL.                       #
#                        The same role can be extended for different flavor   #
#                        of OS or different OS families                       #
###############################################################################
---
###############################################################################
#Listing all the dependencies for this role                                   #
###############################################################################
---
galaxy_info:
  author: The Galaxy Project
  description: Install and manage a PostgreSQL (http://www.postgresql.org/) server.
  company: The Galaxy Project
  license: AFL v3.0
  min_ansible_version: 2.4
  platforms:
  - name: EL
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  galaxy_tags:
  - database
  - sql
  - postgres
  - postgresql
dependencies: []