###############################################################################
#Ansible Role for KPMG Challenge                                              #
#File Name: main.yml                                                          #
###############################################################################
#Developer - Arun Kumar Lakshmi Narayanan                                     #
###############################################################################
#Purpose Of The Script : To install Psotgr SQL on RHEL.                       #
#                        The same role can be extended for different flavor   #
#                        of OS or different OS families                       #
###############################################################################
---
###############################################################################
#Setting up default variables for this role                                   #
###############################################################################

postgresql_default_version: 10
postgresql_backup_local_dir: ~postgres/backup
postgresql_backup_active_dir: "{{ postgresql_backup_local_dir }}/active"
postgresql_backup_mail_recipient: postgres
postgresql_backup_rotate: true
postgresql_user_name: postgres

postgresql_archive_wal_rsync_args: '--ignore-existing -ptg --info=skip1'